### PR TITLE
Enabling openmp threads via --enable-openmp

### PR DESCRIPTION
**Pull request by rainwoodman**
This patch will allow the code to build/link cleanly with --enable-openmp .
Note that --enable-threads seem to be broken.

Some initial benchmarks suggest at 16 threads / rank the penalty due to threads (instead of ranks) is

512 Ranks, 0.832 secons
32 Ranks / 16 threads, 1.23 seconds

pfft_forw_trafo*, pfft_forw_remap* are both seeing the penalty.

### CODE REVIEW

**Comment by mpip** [comment]
Many thanks for your work on the OpenMP support. I will have a closer look on it and merge it into the OpenMP work of my student.

**Comment by mpip** [comment]
--enable-threads is a relict of the old days. It comes from the configure script of FFTW. However, I do not think that PFFT will support pthreads at any time. At the moment this flag does not do anything but telling PFFT that it should check for libfftw3_threads. I think its time to kick it out.

**Comment by mpip** [comment]
I merged your suggestions together with the things that we already in branch cprak-harder.
It is now available in master.

**Comment by mpip** [comment]
Note that the PFFT library is now called pfft_omp.la if OpenMP is enabled. Furthermore, I changed the default behavior to --disable-openmp. So you have to configure with --enable-openmp. Default behavior will change as soon as PFFT works well with OpenMP.

**Comment by mpip** [comment]
I also added OpenMP support to all the Fortran tests.

**Comment by mpip** [comment]
Any comments are appreciated. Again, many thanks for the nice idea of integrating all the FFTW thread init and finalize into pfft_init and pfft_finalize. This makes the usage a lot easier and all the test programs work out of the box.

**Comment by rainwoodman** [comment]
Thanks for merging. I check out the code and confirmed it compiles and works. It makes sense to have a separate file name for the omp library as it imports symbols from the openmp libraries.

**Pull request merged**
